apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 975050229229.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newName: 975050229229.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newTag: 0bc7e19a
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
